---
OrdererOrgs:

  - Name: Orderer
    Domain: orderer.example.com
    EnableNodeOUs: false
    CA:
      Hostname: ca
    Specs:
      - Hostname: router
        Party: party1
        SANS:
          - orderer-router
          - host.docker.internal
          - 0.0.0.0
          - localhost
          - 127.0.0.1
          - ::1
      - Hostname: batcher1
        Party: party1
        SANS:
          - orderer-batcher
          - host.docker.internal
          - 0.0.0.0
          - localhost
          - 127.0.0.1
          - ::1
      - Hostname: consenter
        Party: party1
        SANS:
          - orderer-consenter
          - host.docker.internal
          - 0.0.0.0
          - localhost
          - 127.0.0.1
          - ::1
      - Hostname: assembler
        Party: party1
        SANS:
          - orderer-assembler
          - host.docker.internal
          - 0.0.0.0
          - localhost
          - 127.0.0.1
          - ::1
    Users:
      Count: 1


PeerOrgs:
  # <%_ fabricX.applicationOrgs.forEach((appOrg) => { _%>
  - Name: <%= appOrg.name %>
    Domain: <%= appOrg.domain %>
    EnableNodeOUs: false
    CA:
      hostname: ca
      SANS:
        - 0.0.0.0
        - localhost
        - 127.0.0.1
        - ::1
    Users:
      Count: 1
      Specs:
        - Name: channel_admin
          HSM: false
    Specs:
      - Hostname: committer-sidecar
        SANS:
          - committer-<%= appOrg.slug %>-sidecar
          - host.docker.internal
          - 0.0.0.0
          - localhost
          - 127.0.0.1
          - ::1
      - Hostname: committer-coordinator
        SANS:
          - committer-<%= appOrg.slug %>-coordinator
          - host.docker.internal
          - 0.0.0.0
          - localhost
          - 127.0.0.1
          - ::1
      - Hostname: committer-validator
        SANS:
          - committer-<%= appOrg.slug %>-validator
          - host.docker.internal
          - 0.0.0.0
          - localhost
          - 127.0.0.1
          - ::1
      - Hostname: committer-verifier
        SANS:
          - committer-<%= appOrg.slug %>-verifier
          - host.docker.internal
          - 0.0.0.0
          - localhost
          - 127.0.0.1
          - ::1
      - Hostname: committer-query-service
        SANS:
          - committer-<%= appOrg.slug %>-query-service
          - host.docker.internal
          - 0.0.0.0
          - localhost
          - 127.0.0.1
          - ::1
      - Hostname: endorser
        SANS:
          - host.docker.internal
          - 0.0.0.0
          - localhost
          - 127.0.0.1
          - ::1
      - Hostname: fxconfig
        SANS:
          - host.docker.internal
          - 0.0.0.0
          - localhost
          - 127.0.0.1
          - ::1
  # <%_ }); _%>
